require:
  - rubocop-rails

AllCops:
  Exclude:
    - test/**/* # TODO: Clear all offenses from this folder
    - config/**/* # TODO: Clear all offenses from this folder
    - db/migrate/* # TODO: Clear all offenses from this folder
    - bin/*
    - node_modules/**/*
  NewCops: enable

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 300
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - test/**/*
    - config/**/*
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: true
  EnforcedStyle: no_braces
