defaults: &defaults
  google_client_id: <%= ENV.fetch('GOOGLE_CLIENT_ID') { nil } %>
  domains_allowlist: <%= ENV.fetch('DOMAINS_ALLOWLIST') { '' } %>
  smtp_username: <%= ENV.fetch('SMTP_USERNAME') { 'noreply@docto-retrospective.herokuapp.com' } %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
